services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./data:/data
      - ./scripts:/scripts
    restart: unless-stopped
volumes:
  mongodb_data:
